language: node_js
dist: xenial

node_js:
  - node
  - 16
  - 14
  - 12
  - 10
  - 8

os: 
  - linux
  - windows

jobs:
  include:
    - name: lint
      script: npm run lint
    - name: coveralls
      script: npm run test && npm run coveralls

install: npm install
script: npm run test